import assert from "node:assert/strict";
import test from "node:test";
import { readFile, readdir } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { verificationResultSchema } from "../src/lib/verification/schema";

test("credential migrations enforce ownership, private publication, exact lookup, status, logs and rate limits", async () => {
  const db = new PGlite();
  const alice = "11111111-1111-4111-8111-111111111111";
  const bob = "22222222-2222-4222-8222-222222222222";
  const id = "UZY-CERT-2026-A82KD";
  const hash = "a".repeat(64);
  try {
    await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth; grant usage on schema auth to authenticated;
      create table auth.users(id uuid primary key, email text, email_confirmed_at timestamptz);
      create function auth.uid() returns uuid language sql stable as 'select nullif(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';
      create schema storage;
      create table storage.buckets(id text primary key, name text, public boolean, file_size_limit bigint, allowed_mime_types text[]);
      create table storage.objects(id uuid primary key default gen_random_uuid(), bucket_id text references storage.buckets(id), name text not null);
      alter table storage.objects enable row level security;
      grant usage on schema storage to anon, authenticated, service_role;
      grant select,insert,update,delete on storage.objects to authenticated;
      grant all on storage.objects, storage.buckets to service_role;
      insert into auth.users values ('${alice}', 'alice@example.com', now());`);
    const migrations = new URL("../supabase/migrations/", import.meta.url);
    for (const file of (await readdir(migrations)).filter((f) => f.endsWith(".sql")).sort()) await db.exec(await readFile(new URL(file, migrations), "utf8"));
    await db.exec(`insert into auth.users values ('${bob}', 'bob@example.com', now());`);
    assert.equal((await db.query("select * from public.profiles")).rows.length, 2, "backfill and new-user trigger");
    await db.exec(`insert into public.credentials(credential_id, owner_id, credential_type, category, title, issue_date, public_holder_name, certificate_file_url)
      values ('${id}', '${alice}', 'COURSE_CERTIFICATE', 'COURSE', 'Security Engineering', current_date, 'Alice Approved', 'private/secret.pdf');
      insert into public.badges(name,slug,category,icon_url) values ('Security','security','SECURITY','/badges/cybersecurity.png');
      insert into public.credential_badges select c.id,b.id from public.credentials c cross join public.badges b;`);
    for (const role of ["anon", "authenticated"]) {
      await db.exec(`set role ${role}`);
      await assert.rejects(db.query("select public.verify_public_credential($1,$2)", [id, hash]), /permission denied/);
      await assert.rejects(db.query("select * from public.verification_logs"), /permission denied/);
      await assert.rejects(db.query("select * from public.verification_rate_limits"), /permission denied/);
      assert.equal((await db.query("select * from public.badges")).rows.length, 1);
      await db.exec("reset role");
    }
    await db.exec("set role anon");
    await assert.rejects(db.query("select * from public.profiles"), /permission denied/);
    await assert.rejects(db.query("select * from public.credentials"), /permission denied/);
    await db.exec("reset role; set role authenticated");
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [alice]);
    assert.equal((await db.query("select * from public.profiles")).rows.length, 1);
    assert.equal((await db.query("select * from public.credentials")).rows.length, 0, "candidates cannot see pre-issuance drafts");
    assert.equal((await db.query("select * from public.credential_badges")).rows.length, 0);
    await db.query("update public.profiles set full_name='User edited name' where id=$1", [alice]);
    assert.equal((await db.query("update public.profiles set full_name='Attack' where id=$1 returning id", [bob])).rows.length, 0);
    await db.query("update public.profiles set username='alice-sec', visibility='public' where id=$1", [alice]);
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [bob]);
    await assert.rejects(db.query("update public.profiles set visibility='public' where id=$1", [bob]), /profiles_public_complete/);
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [alice]);
    await db.query("insert into storage.objects(bucket_id,name) values ('avatars',$1)", [`${alice}/draft-33333333-3333-4333-8333-333333333333.webp`]);
    await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values ('avatars',$1)", [`${bob}/draft-44444444-4444-4444-8444-444444444444.webp`]), /row-level security/);
    await db.query("delete from storage.objects where bucket_id='avatars'");
    assert.equal((await db.query("select * from storage.objects")).rows.length, 0, "owner can delete own image");
    await assert.rejects(db.query("update public.profiles set id=$1", [bob]), /permission denied/);
    assert.equal((await db.query("update public.credentials set title='Unauthorized' returning id")).rows.length, 0, "non-issuer cannot update credentials");
    await assert.rejects(db.query("delete from public.credentials"), /permission denied/);
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [bob]);
    assert.equal((await db.query("select * from public.credentials")).rows.length, 0);
    assert.equal((await db.query("select * from public.credential_badges")).rows.length, 0);
    await db.exec("reset role; set role service_role");
    assert.equal((await db.query<{ profile: unknown }>("select public.get_public_profile('missing') as profile")).rows[0].profile, null, "private or missing profile hidden");
    const projected = JSON.stringify((await db.query<{ profile: unknown }>("select public.get_public_profile('alice-sec') as profile")).rows[0].profile);
    assert.match(projected, /User edited name/);
    assert.doesNotMatch(projected, /alice@example.com|11111111-1111-4111-8111-111111111111|private\/secret/);
    const lookup = async (requested = id, key = hash) => verificationResultSchema.parse((await db.query<{ result: unknown }>("select public.verify_public_credential($1,$2) as result", [requested, key])).rows[0].result);
    assert.equal((await lookup()).outcome, "not_found", "private credential indistinguishable from missing");
    await db.exec(`update public.credentials set status='ISSUED', public_visible=true, issued_at=now()`);
    const found = await lookup();
    assert.equal(found.outcome, "found");
    if (found.outcome !== "found") throw new Error("Expected published credential");
    assert.equal(found.credential.holder_name, "Alice Approved");
    assert.equal(found.credential.badges.length, 1);
    const raw = JSON.stringify((await db.query("select public.verify_public_credential($1,$2)", [id, hash])).rows);
    for (const privateField of ["owner_id", "email", "certificate_file_url", "verification_hash", "private/secret", "User edited name"]) assert.ok(!raw.includes(privateField), privateField);
    for (const status of ["REVOKED", "EXPIRED"]) {
      await db.query("update public.credentials set status=$1::public.credential_status, revoked_at=case when $1='REVOKED' then now() else null end, revocation_reason=case when $1='REVOKED' then 'Policy violation' else null end", [status]);
      const value = await lookup(); assert.ok(value.outcome === "found" && value.credential.status === status);
    }
    await db.exec("update public.credentials set status='ISSUED', revoked_at=null, revocation_reason=null, issue_date=current_date-2, expiry_date=current_date-1");
    let value = await lookup(); assert.ok(value.outcome === "found" && value.credential.status === "EXPIRED");
    await db.exec("update public.credentials set expiry_date=null, issue_date=current_date+1");
    value = await lookup(); assert.ok(value.outcome === "found" && value.credential.status === "ISSUED");
    assert.equal((await lookup("UZY-CERT-2026-NOMATCH")).outcome, "not_found");
    assert.equal((await lookup("%" )).outcome, "not_found");
    const limitHash = "b".repeat(64);
    for (let i = 0; i < 30; i++) assert.notEqual((await lookup(id, limitHash)).outcome, "rate_limited");
    assert.equal((await lookup(id, limitHash)).outcome, "rate_limited");
    await db.query("update public.verification_rate_limits set window_start=now()-interval '2 minutes' where requester_hash=$1", [limitHash]);
    assert.equal((await lookup(id, limitHash)).outcome, "found");
    const logs = await db.query<{ ip_address: null }>("select ip_address from public.verification_logs");
    assert.ok(logs.rows.length > 0 && logs.rows.every((l) => l.ip_address === null));
    await db.exec("update public.verification_logs set verified_at=now()-interval '31 days'; select public.prune_verification_activity()");
    assert.equal((await db.query("select * from public.verification_logs")).rows.length, 0);
  } finally { await db.close(); }
});
