"use client";
import { useActionState } from "react";
import { saveProfileAction } from "@/lib/candidate/actions";
import type { Profile } from "@/lib/candidate/schema";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
const fields = [
  ["full_name", "Full name", 160, true], ["username", "Username", 40, true], ["headline", "Professional headline", 160, false],
  ["country", "Country", 100, false], ["linkedin_url", "LinkedIn URL", 2048, false], ["github_url", "GitHub URL", 2048, false], ["portfolio_url", "Portfolio URL", 2048, false],
] as const;
export function ProfileForm({ profile }: { profile: Profile }) {
  const [state, action, pending] = useActionState(saveProfileAction, { status: "idle" });
  return <form action={action} className="space-y-6 rounded-xl border border-border bg-card p-6"><h2 className="text-lg font-semibold">Professional details</h2><div className="grid gap-5 sm:grid-cols-2">{fields.map(([name, label, max, required]) => <label key={name} className="block space-y-2 text-sm"><span>{label}{required ? " *" : ""}</span><Input name={name} type={name.endsWith("_url") ? "url" : "text"} defaultValue={profile[name] || ""} maxLength={max} required={required} disabled={pending} autoComplete={name === "full_name" ? "name" : name === "country" ? "country-name" : "off"} pattern={name === "username" ? "[a-z0-9][a-z0-9_-]{2,39}" : undefined} aria-describedby={name === "username" ? "username-hint" : undefined} />{name === "username" && <span id="username-hint" className="block text-xs text-muted-foreground">3-40 lowercase letters, numbers, underscores or hyphens. Changing this changes your public profile link.</span>}</label>)}</div><label className="block space-y-2 text-sm"><span>Biography</span><textarea name="bio" defaultValue={profile.bio || ""} maxLength={2000} rows={5} disabled={pending} className="w-full rounded-md border border-input bg-background p-3 outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label><fieldset className="space-y-3"><legend className="mb-2 text-sm font-medium">Profile visibility</legend><label className="flex items-start gap-3 text-sm"><input type="radio" name="visibility" value="private" defaultChecked={profile.visibility === "private"} disabled={pending} className="mt-1 accent-primary" /><span>Private<span className="mt-1 block text-xs text-muted-foreground">Only you can view your profile and photo.</span></span></label><label className="flex items-start gap-3 text-sm"><input type="radio" name="visibility" value="public" defaultChecked={profile.visibility === "public"} disabled={pending} className="mt-1 accent-primary" /><span>Public<span className="mt-1 block text-xs text-muted-foreground">Anyone can view your details, photo and issuer-published credentials. Your account email stays private.</span></span></label><p className="text-xs text-muted-foreground">Profile visibility does not change an issuer-published credential&apos;s verification page.</p></fieldset><p role="status" className={`text-sm ${state.status === "error" ? "text-destructive" : "text-primary"}`}>{state.message}</p><Button disabled={pending}>{pending ? "Saving..." : "Save profile"}</Button></form>;
}
