import Link from "next/link";
import Image from "next/image";
import {notFound} from "next/navigation";
import {headers} from "next/headers";
import type {Metadata} from "next";
import {verifyCredential} from "@/lib/verification/service";
import {credentialIdSchema} from "@/lib/verification/schema";
import {getSiteUrl,pageMetadata} from "@/lib/metadata";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Avatar} from "@/components/candidate/avatar";
import {ShareActions} from "@/components/verification/share-actions";
import {Button} from "@/components/ui/button";
type Props={params:Promise<{credential_id:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const parsed=credentialIdSchema.safeParse((await params).credential_id);return pageMetadata("Credential verification","Review the current status and approved public details of a UZYNTRA Security credential.",parsed.success?`/v/${parsed.data}`:"/verify",false)}
export default async function CredentialPage({params}:Props){const result=await verifyCredential((await params).credential_id);if(result.outcome==="not_found")notFound();if(result.outcome!=="found")return <div className="mx-auto max-w-2xl space-y-6 px-6 py-20"><h1 className="text-3xl font-semibold">{result.outcome==="rate_limited"?"Please wait before checking again":"Verification temporarily unavailable"}</h1><p role="status">{result.outcome==="rate_limited"?"Too many verification requests. Try again in one minute.":"We could not check this credential right now. Please try again later."}</p><Link href="/verify" className="text-primary underline">Return to verification</Link></div>;
 const credential=result.credential;const active=credential.status==="ISSUED";const nonce=(await headers()).get("x-nonce")??undefined;const url=new URL(`/v/${credential.credential_id}`,getSiteUrl()).href;const structured={"@context":"https://schema.org","@type":"EducationalOccupationalCredential",name:credential.title,credentialCategory:credential.category,identifier:credential.credential_id,recognizedBy:{"@type":"Organization",name:credential.issuer},dateCreated:credential.issue_date,about:{"@type":"Person",name:credential.holder_name},url,description:`Credential status: ${credential.status}. Checked against UZYNTRA records.`};
 return <div className="mx-auto max-w-4xl space-y-8 px-6 py-16"><script nonce={nonce} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,"\\u003c")}}/><div className="rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/10 to-card p-6 sm:p-9"><div className="flex flex-wrap items-start justify-between gap-6"><div><p className="font-mono text-xs uppercase tracking-widest text-primary">UZYNTRA Security / Live verification</p><h1 className="mt-3 text-3xl font-semibold">{active?"Verified credential":credential.status==="REVOKED"?"Revoked credential":"Expired credential"}</h1><p className={`mt-4 inline-block rounded-full border px-4 py-2 text-sm font-semibold ${active?"border-primary/40 text-primary":"border-destructive/40 text-destructive"}`}>{active?"Verified · ISSUED":credential.status}</p></div><Image src="/brand/verification-badge.svg" width={88} height={88} alt="UZYNTRA verified record"/></div>{!active&&<p className="mt-4 text-sm">This record is authentic, but it is not currently valid.</p>}</div>
 <Card className="overflow-hidden border-primary/20 bg-card/80 shadow-xl shadow-primary/5"><CardHeader><div className="flex flex-wrap items-center gap-5"><Avatar name={credential.holder_name} src={credential.has_avatar&&credential.profile_username?`/api/avatar?username=${encodeURIComponent(credential.profile_username)}`:null}/><div><p className="text-sm text-muted-foreground">Awarded to {credential.holder_name}</p><CardTitle className="mt-2 text-2xl leading-tight">{credential.title}</CardTitle><p className="mt-2 text-sm text-primary">Issued by {credential.issuer}</p></div></div></CardHeader><CardContent className="space-y-7">{credential.description&&<p className="leading-7 text-muted-foreground">{credential.description}</p>}<div className="flex flex-wrap gap-3"><Button asChild><Link href={`/certificate/${credential.credential_id}`}>View certificate</Link></Button>{active&&<Button asChild variant="outline"><a href={`/api/certificate/${credential.credential_id}`}>Download certificate PDF</a></Button>}</div><dl className="grid gap-4 sm:grid-cols-2">{[["Recipient",credential.holder_name],["Issuer",credential.issuer],["Credential ID",credential.credential_id],["Certificate slug",credential.certificate_slug],["Category",credential.category.replaceAll("_"," ")],["Issue date",credential.issue_date],["Expiration date",credential.expiry_date??"No expiration"]].map(([label,value])=><div className="rounded-lg border bg-background/40 p-4" key={label}><dt className="text-xs uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-2 break-words text-sm font-medium">{value}</dd></div>)}</dl><div className="flex flex-wrap items-center gap-6 rounded-xl border bg-background/50 p-4"><Image src={`/api/qr/${credential.credential_id}`} width={150} height={150} alt="QR code for this verification URL" unoptimized/><div className="min-w-0 flex-1"><p className="text-sm font-medium">Scan to verify</p><p className="mt-2 break-all font-mono text-xs text-muted-foreground">{url}</p></div></div><ShareActions credentialId={credential.credential_id} title={credential.title} recipient={credential.holder_name}/></CardContent></Card>
 {credential.badges.length>0&&<section aria-labelledby="badges-heading"><h2 id="badges-heading" className="mb-4 text-xl font-semibold">Associated badges</h2><div className="grid gap-4 sm:grid-cols-2">{credential.badges.map(badge=><div key={badge.slug} className="flex items-center gap-4 rounded-xl border p-4"><Image src={badge.icon_url} width={80} height={80} alt="" className="size-20 object-contain"/><div><h3 className="font-medium">{badge.name}</h3><p className="text-sm text-muted-foreground">{badge.level??badge.category}</p></div></div>)}</div></section>}
 <p className="text-sm text-muted-foreground">Verified against UZYNTRA records at <time dateTime={credential.verified_at}>{new Date(credential.verified_at).toLocaleString("en-US",{dateStyle:"long",timeStyle:"long",timeZone:"UTC"})} UTC</time>. Revisit this URL for the latest status.</p><Link href="/verify" className="text-primary underline">Verify another credential</Link></div>}
