"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {uploadBadgeAction} from "@/lib/issuer/actions";
import {validateAvatarFile} from "@/lib/candidate/avatar";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
export function BadgeUpload({userId}:{userId:string}){const router=useRouter();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");let path="";try{const form=new FormData(e.currentTarget);const file=form.get("file");if(!(file instanceof File))throw new Error("Choose a badge image.");validateAvatarFile(file);await createImageBitmap(file);path=`${userId}/draft-${crypto.randomUUID()}.${file.type==="image/webp"?"webp":file.type==="image/png"?"png":"jpg"}`;const client=createClient();const up=await client.storage.from("badge-artwork").upload(path,file,{contentType:file.type});if(up.error)throw new Error("Badge upload failed.");const result=await uploadBadgeAction({name:form.get("name"),slug:form.get("slug"),category:form.get("category"),level:form.get("level"),draft_path:path});setMsg(result.message||"");if(result.status==="success"){e.currentTarget.reset();router.refresh();}}catch(error){setMsg(error instanceof Error?error.message:"Badge upload failed.");}finally{if(path)await createClient().storage.from("badge-artwork").remove([path]);setBusy(false);}}return <form onSubmit={submit} className="grid gap-4 rounded-xl border bg-card p-6 sm:grid-cols-2"><label className="text-sm">Name *<Input name="name" required/></label><label className="text-sm">Slug *<Input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"/></label><label className="text-sm">Category<select name="category" className="mt-2 h-10 w-full rounded-md border bg-background px-3">{["COURSE","SECURITY","CONTRIBUTION","INTERNSHIP","RECOGNITION"].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm">Level<Input name="level"/></label><label className="text-sm sm:col-span-2">Artwork *<Input name="file" type="file" accept="image/png,image/jpeg,image/webp" required/></label><div className="sm:col-span-2"><p role="status" className="text-sm text-primary">{msg}</p><Button className="mt-3" disabled={busy}>{busy?"Uploading...":"Upload badge"}</Button></div></form>}
